### ISSUE TITLE
Question: Building  & Missing V3Ast_gen.... files

### ISSUE THREAD

**Issue by veripoolbot** [verilator/verilator#1739]
---

Author Name: **Yehuda Singer**
Original Redmine Message: 669 from https://www.veripool.org

---

Dear sir/Mrs. 

I installed the Verilator on a Fedora machine and the missing files wew fond in two new folder named obj_dbg and obg_opt.
Now I want to build the verilator in EClipse CDT. 
1. I added the pathto the systemc.h file.
2. I get compilation errors in the Vast_gen_... files.

I work on Ubuntu 11.0

Best regards,
Yehuda
