### ISSUE TITLE
compile errors with typedef structs in parametrized modules

### ISSUE THREAD

**Issue by iank** [verilator/verilator#7920]
> Can you please attach an example that shows the issue or missing feature?

I apologize that both of these testcases are hard to follow, they are minimized versions of issues I encountered in a proprietary project.

https://github.com/iank/verilator/blob/fix-typedef-struct-redefinition/test_regress/t/t_typedef_redefinition.v
https://github.com/iank/verilator/blob/fix-typedef-struct-redefinition/test_regress/t/t_typedef_struct_include_cycle.v

They are both compilation errors in the emitted C++. As far as I can tell what's happening is that the parametrized modules should cause these structures to get unique names, or sometimes the hierarchy can get flattened and the struct definition ends up inlined somewhere else. When one parametrization is prevented from being inlined (e.g. by `verilator no_linline_module` or `verilator public` somewhere), but another is allowed to be inlined, I think this can cause multiple and/or missing definitions in the generated headers.

> What output from that test indicates it is wrong, and what is the correct or expected output?  (Or, please make test self-checking if possible.)

Both lint and generate C++ but fails to compile:

```
[nix-shell:~/verilator-master]$ ./bin/verilator --lint-only test_regress/t/t_typedef_redefinition.v
- V e r i l a t i o n   R e p o r t: Verilator 5.051 devel rev vUNKNOWN-built19800101-52287c025
- Verilator: Built from 0.031 MB sources in 4 modules, into 0.012 MB in 5 C++ files needing 0.000 MB
- Verilator: Walltime 0.023 s (elab=0.001, cvt=0.005, bld=0.000); cpu 0.023 s on 1 threads; allocated 23.660 MB
(.venv)
[nix-shell:~/verilator-master]$ ./bin/verilator --binary test_regress/t/t_typedef_redefinition.v
make: Entering directory '/home/ian/verilator-master/obj_dir'
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o verilated.o /home/ian/verilator-master/include/verilated.cpp
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o verilated_threads.o /home/ian/verilator-master/include/verilated_threads.cpp
python3 /home/ian/verilator-master/bin/verilator_includer -DVL_INCLUDE_OPT=include Vt_typedef_redefinition.cpp Vt_typedef_redefinition___024root__0.cpp Vt_typedef_redefinition_wrap_mod__0.cpp Vt_typedef_redefinition__main.cpp Vt_typedef_redefinition___024root__Slow.cpp Vt_typedef_redefinition___024root__0__Slow.cpp Vt_typedef_redefinition_wrap_mod__Slow.cpp Vt_typedef_redefinition_wrap_mod__0__Slow.cpp Vt_typedef_redefinition__Syms__Slow.cpp > Vt_typedef_redefinition__ALL.cpp
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o Vt_typedef_redefinition__ALL.o Vt_typedef_redefinition__ALL.cpp
In file included from Vt_typedef_redefinition__Syms.h:17,
                 from Vt_typedef_redefinition__pch.h:22,
                 from Vt_typedef_redefinition.cpp:4,
                 from Vt_typedef_redefinition__ALL.cpp:3:
Vt_typedef_redefinition___024root.h:13:8: error: redefinition of ‘struct Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0’
   13 | struct Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0 {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Vt_typedef_redefinition.h:15,
                 from Vt_typedef_redefinition__Syms.h:14:
Vt_typedef_redefinition_wrap_mod.h:13:8: note: previous definition of ‘struct Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0’
   13 | struct Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0 {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_redefinition___024root.h:30:8: error: redefinition of ‘struct VlIsCustomStruct<Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0>’
   30 | struct VlIsCustomStruct<Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0> : public std::true_type {};
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_redefinition_wrap_mod.h:30:8: note: previous definition of ‘struct VlIsCustomStruct<Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0>’
   30 | struct VlIsCustomStruct<Vt_typedef_redefinition_td_inst__DOT__td_struct_t__struct__0> : public std::true_type {};
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/home/ian/verilator-master/include/verilated.mk:290: Vt_typedef_redefinition__ALL.o] Error 1
make: Leaving directory '/home/ian/verilator-master/obj_dir'
%Error: 'make -C obj_dir -f Vt_typedef_redefinition.mk -j 1' exited with 2
        ... See the manual at https://verilator.org/verilator_doc.html?v=5.051 for more assistance.
%Error: Command Failed ulimit -s unlimited 2>/dev/null; exec /home/ian/verilator-master/bin/verilator_bin --binary test_regress/t/t_typedef_redefinition.v
```

```
[nix-shell:~/verilator-master]$ ./bin/verilator --lint-only test_regress/t/t_typedef_struct_include_cycle.v
- V e r i l a t i o n   R e p o r t: Verilator 5.051 devel rev vUNKNOWN-built19800101-52287c025
- Verilator: Built from 0.032 MB sources in 6 modules, into 0.014 MB in 5 C++ files needing 0.000 MB
- Verilator: Walltime 0.025 s (elab=0.002, cvt=0.007, bld=0.000); cpu 0.025 s on 1 threads; allocated 23.832 MB
(.venv)
[nix-shell:~/verilator-master]$ ./bin/verilator --binary test_regress/t/t_typedef_struct_include_cycle.v
make: Entering directory '/home/ian/verilator-master/obj_dir'
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o verilated.o /home/ian/verilator-master/include/verilated.cpp
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o verilated_threads.o /home/ian/verilator-master/include/verilated_threads.cpp
python3 /home/ian/verilator-master/bin/verilator_includer -DVL_INCLUDE_OPT=include Vt_typedef_struct_include_cycle.cpp Vt_typedef_struct_include_cycle___024root__0.cpp Vt_typedef_struct_include_cycle_branch_b__0.cpp Vt_typedef_struct_include_cycle__main.cpp Vt_typedef_struct_include_cycle___024root__Slow.cpp Vt_typedef_struct_include_cycle___024root__0__Slow.cpp Vt_typedef_struct_include_cycle_branch_b__Slow.cpp Vt_typedef_struct_include_cycle_branch_b__0__Slow.cpp Vt_typedef_struct_include_cycle__Syms__Slow.cpp > Vt_typedef_struct_include_cycle__ALL.cpp
g++ -Os  -I.  -MMD -I/home/ian/verilator-master/include -I/home/ian/verilator-master/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -DVM_VPI=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o Vt_typedef_struct_include_cycle__ALL.o Vt_typedef_struct_include_cycle__ALL.cpp
In file included from Vt_typedef_struct_include_cycle_branch_b.h:9,
                 from Vt_typedef_struct_include_cycle.h:15,
                 from Vt_typedef_struct_include_cycle__Syms.h:14,
                 from Vt_typedef_struct_include_cycle__pch.h:22,
                 from Vt_typedef_struct_include_cycle.cpp:4,
                 from Vt_typedef_struct_include_cycle__ALL.cpp:3:
Vt_typedef_struct_include_cycle___024root.h:54:5: error: ‘Vt_typedef_struct_include_cycle_branch_b’ does not name a type; did you mean ‘Vt_typedef_struct_include_cycle__Syms’?
   54 |     Vt_typedef_struct_include_cycle_branch_b* __PVT__t__DOT__bb_inst;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     Vt_typedef_struct_include_cycle__Syms
Vt_typedef_struct_include_cycle_branch_b.h:32:8: error: redefinition of ‘struct Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0’
   32 | struct Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0 {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_struct_include_cycle___024root.h:32:8: note: previous definition of ‘struct Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0’
   32 | struct Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0 {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_struct_include_cycle_branch_b.h:49:8: error: redefinition of ‘struct VlIsCustomStruct<Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0>’
   49 | struct VlIsCustomStruct<Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0> : public std::true_type {};
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_struct_include_cycle___024root.h:49:8: note: previous definition of ‘struct VlIsCustomStruct<Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0>’
   49 | struct VlIsCustomStruct<Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0> : public std::true_type {};
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_struct_include_cycle.cpp: In constructor ‘Vt_typedef_struct_include_cycle::Vt_typedef_struct_include_cycle(VerilatedContext*, const char*)’:
Vt_typedef_struct_include_cycle.cpp:13:43: error: ‘class Vt_typedef_struct_include_cycle___024root’ has no member named ‘__PVT__t__DOT__bb_inst’
   13 |     , __PVT__t__DOT__bb_inst{vlSymsp->TOP.__PVT__t__DOT__bb_inst}
      |                                           ^~~~~~~~~~~~~~~~~~~~~~
Vt_typedef_struct_include_cycle.cpp:13:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘Vt_typedef_struct_include_cycle_branch_b* const’ in initialization
   13 |     , __PVT__t__DOT__bb_inst{vlSymsp->TOP.__PVT__t__DOT__bb_inst}
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Vt_typedef_struct_include_cycle__ALL.cpp:11:
Vt_typedef_struct_include_cycle__Syms__Slow.cpp: In constructor ‘Vt_typedef_struct_include_cycle__Syms::Vt_typedef_struct_include_cycle__Syms(VerilatedContext*, const char*, Vt_typedef_struct_include_cycle*)’:
Vt_typedef_struct_include_cycle__Syms__Slow.cpp:21:9: error: ‘class Vt_typedef_struct_include_cycle___024root’ has no member named ‘__PVT__t__DOT__bb_inst’
   21 |     TOP.__PVT__t__DOT__bb_inst = &TOP__t__DOT__bb_inst;
      |         ^~~~~~~~~~~~~~~~~~~~~~
make: *** [/home/ian/verilator-master/include/verilated.mk:290: Vt_typedef_struct_include_cycle__ALL.o] Error 1
make: Leaving directory '/home/ian/verilator-master/obj_dir'
%Error: 'make -C obj_dir -f Vt_typedef_struct_include_cycle.mk -j 1' exited with 2
        ... See the manual at https://verilator.org/verilator_doc.html?v=5.051 for more assistance.
%Error: Command Failed ulimit -s unlimited 2>/dev/null; exec /home/ian/verilator-master/bin/verilator_bin --binary test_regress/t/t_typedef_struct_include_cycle.v
```
> What 'verilator' command line do we use to run your example?

See above

> What 'verilator --version' are you using?  Did you try it with the git master version?  Did you try it with other simulators?

```
Verilator 5.051 devel rev vUNKNOWN-built19800101-52287c025
```

Current master branch (52287c02). The original code simulated okay under xsim, and worked in hardware (Vivado 2023.1 synthesis/implementation), but I have not tested these minimized testcases in xsim.

> What OS and distribution are you using?

Ubuntu 24.04 and NixOS 26.05

> May we assist you in trying to fix this in Verilator yourself?

Yes! I have a fix that passes all of the tests but it involves emitting all of the struct definitions to a shared header. I'm not sure if that's the right approach, and I'm not familiar enough with verilator internals to have confidence my changes are correct.

**Comment by wsnyder** [comment]
If you can debug it would be appreciated.  We don't want to change to a shared header; it should work with a header per struct, and and the proper includes for those headers, so perhaps an include is what's missing.

**Comment by iank** [comment]
Ok, happy to try and debug. I minimized the testcases a little bit more. The first one now looks like:

```
module t (
    input clk
);
  logic i = 0;
  logic a, b;
  int cyc = 0;

  always_ff @(posedge clk) i <= ~i;
  sub_mod sub_inst (.clk(clk), .in(i), .out(a));
  wrap_mod wrap_inst (.clk(clk), .in(i), .out(b));

  always @(posedge clk) begin
    cyc <= cyc + 1;
    if (cyc > 2 && a != b) $stop;
    if (cyc == 10) begin
      $write("*-* All Finished *-*\n");
      $finish;
    end
  end
endmodule

module wrap_mod (
    input logic clk,
    input logic in,
    output logic out
);
  /*verilator no_inline_module*/
  sub_mod sub_inst (.clk(clk), .in(in), .out(out));
endmodule

module sub_mod (
    input logic clk,
    input logic in,
    output logic out
);
  typedef struct {logic x;} td_struct_t;

  td_struct_t r;
  always_ff @(posedge clk) r.x <= in;
  assign out = r.x;
endmodule
```

So there's two sub_mod instances. One gets inlined into the root and the other (via wrap_mod) is not. We end up with a definition for `Vt_typedef_redefinition_sub_inst__DOT__td_struct_t__struct__0` in both `Vt_typedef_redefinition_wrap_mod.h` and `Vt_typedef_redefinition___024root.h`.

The second testcase is still pretty long:

```
module t (
    input clk
);
  logic i = 0;
  logic a, b;
  int cyc = 0;

  always_ff @(posedge clk) i <= ~i;
  holder_mod #(.P(1)) ha_inst (.clk(clk), .din(i), .o(a));
  branch_b bb_inst (.clk(clk), .din(i), .o(b));

  always @(posedge clk) begin
    cyc <= cyc + 1;
    if (cyc > 4 && a != ~b) $stop;
    if (cyc == 10) begin
      $write("*-* All Finished *-*\n");
      $finish;
    end
  end
endmodule

module branch_b (
    input logic clk,
    input logic din,
    output logic o
);
  /*verilator no_inline_module*/
  holder_mod #(.P(0)) h_inst (.clk(clk), .din(din), .o(o));
endmodule

module holder_mod #(
    parameter int P = 0
) (
    input logic clk,
    input logic din,
    output logic o
);
  typedef struct {logic f;} s_t;

  logic u_out, s_out;

  user_mod #(.T(s_t)) u_inst (.clk(clk), .din(din), .dout(u_out));
  shared_mod sh_inst (.clk(clk), .din(din), .sout(s_out));

  assign o = u_out ^ s_out ^ P[0];
endmodule

module user_mod #(
    parameter type T = logic
) (
    input logic clk,
    input logic din,
    output logic dout
);
  T v;
  always_ff @(posedge clk) v.f <= din;
  assign dout = v.f;
endmodule

module shared_mod (
    input logic clk,
    input logic din,
    output logic sout
);
  typedef struct {logic g;} shared_t;

  shared_t sh;
  always_ff @(posedge clk) sh.g <= din;
  assign sout = sh.g;
endmodule
```

Here we end up with a root module and a branch_b module. The root header defines `Vt_typedef_struct_include_cycle_t__DOT__ha_inst__DOT__s_t__struct__0`, the branch_b header defines `Vt_typedef_struct_include_cycle_h_inst__DOT__sh_inst__DOT__shared_t__struct__0`. But both headers use both struct types so there's a cycle.

In the first case we could probably get away with just tweaking the ownership mechanism so that struct definition is only emitted once, although I'm not sure about the soundness of that change in general. It's less clear (to me) what to do about the second case.

I don't mean to be pedantic but when you said "it should work with a header per struct" did you mean that exactly (it's not what's happening now)? If so then I'd be happy to take a crack at implementing that, I think it's the simplest solution (at least the correctness would be easy to reason about). If on the other hand you want to stick closer to the current structure I will dig deeper but I'll probably need more guidance.

**Comment by wsnyder** [comment]
Currently structs are defined as part of the containing class/module/package.  So if the `typedef struct {logic x;} td_struct_t;` is moved to the $unit scope it will go into the common __024unit.h file, both will use it, and all seems well.

Note both seem to work with -fno-inline so that suggests the problem is only related to inline cloning and V3Inline (ideally) is the only one needing changes.

If the inliner renames the struct it seems that should fix your example 1.  I don't understand how that would lead to circular definitions you mention, given that -fno-inline seems to work ok.
