### ISSUE TITLE
Regression during compilation of Verilated output - "invalid use of non-static data member"

### ISSUE THREAD

**Issue by em2machine** [verilator/verilator#6659]
During compilation of the Verilated RTL:

```
./Vaerial_wrap_pf__03a__03abrshift_c__P6__Vclpkg__0.cpp:220:49: error: invalid use of non-static data member '__Vlvbound_hdb1999c9__0'
  220 |         Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vaerial_wrap_pf__03a__03abrshift_c__P6__Vclpkg__0.cpp:224:99: error: invalid use of non-static data member '__Vlvbound_hdb1999c9__0'
  224 |                      & (IData)(outb)) | (0x3fU & ((IData)(Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0) 
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

```
By hand editing the output and declaring '`__Vlvbound_hdb1999c9__0`' locally it builds (and test regression passes).

  ```
  // EOM
     CData/*0:0*/ __Vlvbound_hdb1999c9__0;
     __Vlvbound_hdb1999c9__0 = 0;


            outb = (((~ ((IData)(1U) << (7U & i))) 
                     //& (IData)(outb)) | (0x3fU & ((IData)(Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0) 
		     & (IData)(outb)) | (0x3fU & ((IData)(__Vlvbound_hdb1999c9__0)


        // EOM
	//Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0 
	__Vlvbound_hdb1999c9__0
            = __Vfunc_ohm__0__Vfuncout;
```

Compiler version (unchanged):
```
verilator % /usr/bin/clang++ --version
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
verilator % verilator --version
Verilator 5.043 devel rev v5.042-27-geafad9742
```

Function source (of course this is used in many places parameterized):

   ```
virtual class brshift_c #(parameter p_width=4);
      static function logic[p_width-1:0] brshift(
         input logic[p_width-1:0] inb
         ,input logic[p_width-1:0] sel
      );
         logic [p_width-1:0][p_width-1:0] bus_array;
         logic [p_width-1:0] outb;
         integer i, j;

         assert(p_width>1);

         for(i=0; i<p_width; i++) begin : gen_outer
            for(j=0; j<p_width; j++) begin : gen_inner
               bus_array[i][j] = inb[  ((i+j)>=p_width) ? (i+j)-p_width : (i+j) ];
            end
         end

         for(i=0; i<p_width; i++) begin : gen_bit_mux
            outb[i] = ohm_c#(p_width)::ohm(sel, bus_array[i]);
         end

         brshift = outb;
      endfunction
   endclass
```

Thanks,
-e-

**Comment by wsnyder** [comment]
What change does this git bisect to?

Can you attach a self-contained test case?

**Comment by em2machine** [comment]
Working on the self-contained.  sv-bugpoint doesnt converge, so am trying to bi-sect by hand again ><.

**Comment by em2machine** [comment]
Ok, the following code fails during compilation with the following.  Also, when PqSize is a power of two (2, 4, 8, 16, 32 and then I stopped) it successfully compiles, but for instance 6 or 27 results in the below error.
Thanks,
-e-

```
  -c -o Vtest10__ALL.o Vtest10__ALL.cpp
In file included from Vtest10__ALL.cpp:5:
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:59:45: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   59 |         Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:64:83: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   64 |                     | (0x07ffffffU & ((IData)(Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0) 
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

```
package pf;
   virtual class ohm_c #(parameter p_width=4);
      static function ohm(
         input logic[p_width-1:0] sel
         ,input logic[p_width-1:0] inb
      );
         ohm = '0;
      endfunction
   endclass
   virtual class brshift_c #(parameter p_width=4);
      static function logic[p_width-1:0] brshift(
         input logic[p_width-1:0] inb
         ,input logic[p_width-1:0] sel
      );
         logic [p_width-1:0][p_width-1:0] bus_array;
         logic [p_width-1:0] outb;
         integer i;

         for(i=0; i<p_width; i++) begin : gen_bit_mux
            outb[i] = ohm_c#(p_width)::ohm(sel, bus_array[i]);
         end

         brshift = outb;
      endfunction
   endclass
endpackage

module pri_sel #(parameter int unsigned p_width = 4)(
   input logic [p_width-1:0] inb_i
);
   logic [p_width-1:0] token_q;
   logic [p_width-1:0] pri, ralign;
   assign ralign = pf::brshift_c#(p_width)::brshift(pri, token_q);
endmodule

module the_top();

   localparam int PqSize = 27;

   logic [PqSize-1:0] pq_sc_rq_vld_a;

   pri_sel #(PqSize) pri_sel(
      .inb_i(pq_sc_rq_vld_a)
   );

endmodule

```

**Comment by wsnyder** [comment]
WIth --debug I get a much clearer

`%Error: Internal Error: t/t_0.v:52:45: ../V3Ast.cpp:1196: AstDot must have non nullptr lhsp()
`

I tried a few revs like last stable point and this test seemed to always fail (with --debug), in what rev was it passing?

**Comment by em2machine** [comment]
Ok, some strange behavior...  

```
verilator_fixes % /opt/verilator.20250928/bin/verilator --version         
Verilator 5.041 devel rev v5.040-213-gca0a67941

```
Full design builds.  ><

Bisected test:
```
verilator_fixes % /opt/verilator.20250928/bin/verilator --binary test10.sv
/usr/bin/clang++ -Os -std=c++14 -I.  -MMD -I/opt/verilator.20251107/share/verilator/include -I/opt/verilator.20251107/share/verilator/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Xclang -fno-pch-timestamp -Qunused-arguments -Wno-bool-operation -Wno-c++11-narrowing -Wno-constant-logical-operand -Wno-int-in-bool-context -Wno-non-pod-varargs -Wno-parentheses-equality -Wno-shadow -Wno-sign-compare -Wno-tautological-bitwise-compare -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o Vtest10__ALL.o Vtest10__ALL.cpp
In file included from Vtest10__ALL.cpp:5:
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:59:45: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   59 |         Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:64:83: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   64 |                     | (0x07ffffffU & ((IData)(Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0) 
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

```

Latest:

```
verilator_fixes % verilator --version
Verilator 5.043 devel rev v5.042-27-geafad9742

```
When building the full design:

```
In file included from Vaerial_wrap_vm_classes_7.cpp:144:
./Vaerial_wrap_pf__03a__03abrshift_c__P6__Vclpkg__0.cpp:220:49: error: invalid use of non-static data member '__Vlvbound_hdb1999c9__0'
  220 |         Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vaerial_wrap_pf__03a__03abrshift_c__P6__Vclpkg__0.cpp:224:99: error: invalid use of non-static data member '__Vlvbound_hdb1999c9__0'
  224 |                      & (IData)(outb)) | (0x3fU & ((IData)(Vaerial_wrap_pf__03a__03abrshift_c__P6::__Vlvbound_hdb1999c9__0) 
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from Vaerial_wrap_vm_classes_7.cpp:147:
./Vaerial_wrap_pf__03a__03abrshift_c__P3__Vclpkg__0.cpp:75:49: error: invalid use of non-static data member '__Vlvbound_ha27736e1__0'
   75 |         Vaerial_wrap_pf__03a__03abrshift_c__P3::__Vlvbound_ha27736e1__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vaerial_wrap_pf__03a__03abrshift_c__P3__Vclpkg__0.cpp:79:96: error: invalid use of non-static data member '__Vlvbound_ha27736e1__0'
   79 |                      & (IData)(outb)) | (7U & ((IData)(Vaerial_wrap_pf__03a__03abrshift_c__P3::__Vlvbound_ha27736e1__0) 
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

The bisected testcase:
```

verilator_fixes % /opt/verilator/bin/verilator --binary test10.sv 
/usr/bin/clang++ -Os -std=c++14 -I.  -MMD -I/opt/verilator.20251107/share/verilator/include -I/opt/verilator.20251107/share/verilator/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Xclang -fno-pch-timestamp -Qunused-arguments -Wno-bool-operation -Wno-c++11-narrowing -Wno-constant-logical-operand -Wno-int-in-bool-context -Wno-non-pod-varargs -Wno-parentheses-equality -Wno-shadow -Wno-sign-compare -Wno-tautological-bitwise-compare -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -c -o Vtest10__ALL.o Vtest10__ALL.cpp
In file included from Vtest10__ALL.cpp:5:
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:59:45: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   59 |         Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0 
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
./Vtest10_pf__03a__03abrshift_c__P1b__Vclpkg__0.cpp:64:83: error: invalid use of non-static data member '__Vlvbound_hd8854aa6__0'
   64 |                     | (0x07ffffffU & ((IData)(Vtest10_pf__03a__03abrshift_c__P1b::__Vlvbound_hd8854aa6__0) 
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by em2machine** [comment]
/sigh
When I build the full design with the exact same build script and version that builds (and regresses correctly) but add `--debug`:

```
verilator_fixes % /opt/verilator.20250928/bin/verilator --version         
Verilator 5.041 devel rev v5.040-213-gca0a67941
```

```
- V3Ast.cpp:1397:     Dumping obj_dir/Vaerial_wrap_009_param.tree
%Error: Internal Error: <SNIP>:294:59: ../V3Ast.cpp:1203: AstDot must have non nullptr lhsp()
                                                                           : ... note: In instance '<SNIP>'
-node: DOT 0x60000889b020 <e254424> {dj294ch} @dt=0x0@ [::]
  294 |    assign rdata_select = pf::decoder_c#(ACFG.DataBits/8)::decoder(1'b1, ccom_addr_q[$clog2(ACFG.DataBits/8)-1:0]);
```

**Comment by wsnyder** [comment]
Ok, so basically the small test case has always failed. The double :: might be painful to fix.

Did you try using --debug on gca0a67941 with the full original test - I suspect it fails?

**Comment by wsnyder** [comment]
Messages crossed, that's a yes ;)

Might you look into fixing this?  Presumably V3LinkDot is what needs help.

**Comment by em2machine** [comment]
I'll attempt to poke around.  I'm a bit nervous about other lurking issues when running without --debug, etc.  So I probably have additional investigation to do as well.  Is there any other forum for noob questions on the codebase, or is it all here?

**Comment by wsnyder** [comment]
Great.  BTW you can use '--debug --no-dump-tree' to avoid the .tree files which are most of the reason debug is slower.

Fine to ask questions in this thread, but of course if you find something completely unrelated broken or to fix please make a new issue/pull.

**Comment by em2machine** [comment]
Further simplification to make it easier to look at.

```
%Error: Internal Error: test10.sv:13:37: ../V3Ast.cpp:1197: AstDot must have non nullptr lhsp()
                                       : ... note: In instance 'the_top.modA'
-node: DOT 0x600003b0f910 <e1037> {e13bl} @dt=0x0@ [::]
   13 |    assign sig_b = func_c#(p_width)::func(inb_i);
      |                                     ^~~~
                        ... See the manual at https://verilator.org/verilator_doc.html?v=5.043 for more assistance.
```

```
virtual class func_c #(parameter p_width=4);
   static function logic[p_width-1:0] func(
      input logic[p_width-1:0] inb
   );
      func = 'b0;
   endfunction
endclass

module modA #(parameter int unsigned p_width = 4)(
   input logic [p_width-1:0] inb_i
);
   logic [p_width-1:0] sig_b;
   assign sig_b = func_c#(p_width)::func(inb_i);
endmodule

module the_top();
   localparam int Size = 3;

   logic [Size-1:0] sig_a;

   modA #(Size) modA(
      .inb_i(sig_a)
   );
endmodule
```

obj_dir/Vtest10_009_param.tree:
```
  1:2: ALWAYS 0x6000010cb440 <e1040> {e13ar} [cont_assign]
    1:2:2: ASSIGNW 0x6000016c9400 <e1036> {e13ar} @dt=0x0@
    1:2:2:1: DOT 0x6000010cb4f0 <e1037> {e13bl} @dt=0x0@ [::]
    1:2:2:1:1: CLASSORPACKAGEREF 0x6000012c7f00 <e1034> {e13at} @dt=0x0@  func_c cpkg=0x12c707e40 -> CLASS 0x12c707e40 <e1581#> {e1aj}  func_c__P3  L4 D4 [1ps] [VIRT]
    **1:2:2:1:2: FUNCREF 0x12c707d30 <e1035> {e13bl} @dt=0x0@  func -> UNLINKED**
```

**Comment by em2machine** [comment]
Ok, after staring at it for awhile, it seems like the issue is that we need to specialize the virtual class (which should then specialize any methods in that class).  However we don’t know the specialization until parameterization  (which seems to come after linkdot).   Is this why FUNCREF for the specialization is unlinked?  I.e. the passes attempt to do the node linking, defers the dots until parameterization (at least in this case), but it needs to go back and "relink" after parameter specialization? 

Maybe this is obvious, but its the first time I've ever explored...

**Comment by wsnyder** [comment]
Yes, we link first time to do parameters, then second link once know parameters.

**Comment by em2machine** [comment]
Ok, I think there are multiple issues:

My bisected tests have nested linkdots, with --debug these were hitting the "AstDot must have non nullptr lhsp()" Internal Error.  My naive fix (which breaks some of the uvm regression tests) "fixes" this (by looping over again and looking for nullptr to resolve) and then I still run into the "invalid user of non-static data member" compilation error downstream.  

When I fix that compilation error by hand (like before) my design regression passes.  So I don't think the internal error when --debug is enabled is the root cause of the "invalid user of non-static data member".

I am unfortunately at the limit of what I can comprehend (VParam and VLinkDot ><) in the time I have right now as I have to get back to the design work.  My suspicion is that this would trace all the way back to the conversation we had on an older issue on whether to build a separate graph for params and specialization.  My tactical work around is to remove the nested link dots (specialized class calling specialized class) from my code.

**Comment by wsnyder** [comment]
Thanks for looking into this, glad you can change the Verilog code for now. At some point I'll get to looking into this further.

**Comment by em2machine** [comment]
I'm not sure if its useful or not, but when I uncomment the assign in the top module and comment out the modA instantiation then I don't get an internal error when --debug is enabled.  So this seems to be more focused on specialized class functions in nested modules rather than nested class functions itself...   (Im still lightly looking at this as with HEAD master I can build the OG design and build and run regression, but with --debug enabled still have the LHS nullptr internal error even with my RTL changes - which makes me nervious).

```
class func_c #(parameter p_width=4);
   static function logic[p_width-1:0] func(
      input logic[p_width-1:0] inb
   );
      func = 'h5;
   endfunction
endclass

module modA #(parameter p_width = 7)(
   input logic [p_width-1:0] inb_i
   ,output logic [p_width-1:0] sig_b
);
   assign sig_b = func_c#(p_width)::func(inb_i);
endmodule

module the_top();
   localparam int Size = 3;

   logic [Size-1:0] sig_a;
   logic [Size-1:0] sig_b;

   modA #(.p_width(Size)) modA(
      .inb_i(sig_a)
      ,.sig_b(sig_b)
   );

   //assign sig_b = func_c#(p_width)::func(inb_i);

   initial begin
      #1;
      sig_a = 'h3;
      if(sig_b != 'h5) $stop;
      $write("*-* All Finished *-*\n");
      $finish;
   end
endmodule
```

**Comment by em2machine** [comment]
Ok, coming back to this.  On my simple testcase when --debug is enabled:

```
%Error: Internal Error: test8.sv:13:37: ../V3Ast.cpp:1197: AstDot must have non nullptr lhsp()
                                      : ... note: In instance 'the_top.modA'
-node: DOT (AE) <e1330> {e13bl} @dt=0@ [::]
   13 |    assign sig_b = func_c#(p_width)::func(sig_a);
```

Fix coming with testcases.  In this case the visitor is leaving the lhsp dangling null.

**Comment by em2machine** [comment]
Just as FYI, this also now works (previous --debug also would 'Internal Error'):

```
class func_c #(parameter p_width=4);
  typedef struct packed {
    logic[p_width-1:0] data;
  } my_type_t;
  static function my_type_t func(
    input logic[p_width-1:0] inb
  );
    func.data = inb;
  endfunction
endclass

module modA #(parameter p_width = 7)(
  input func_c#(p_width)::my_type_t sig_a
  ,output func_c#(p_width)::my_type_t sig_b
);
  assign sig_b.data = func_c#(p_width)::func(sig_a);
endmodule
```
