### PR TITLE
Patch developer build on MacOS/Flex2.6.4

### PR DESCRIPTION
**Pull request by paul-demo**
- With export VERILATOR_AUTHOR_SITE=1 and ./configure --enable-longtests, verilator didn't build on M1 Mac 15.5 / Flex 2.6.4 without these changes. It does build with them.
- "Regular user build" has been fine regardless so it must just be some signed-comparison warnings become errors when doing things in "developer mode"

We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Comment by paul-demo** [comment]
Resolves both of these errors:

```
../V3LinkDot.cpp:3361:40: error: variable 'defp' set but not used [-Werror,-Wunused-but-set-variable]
 3361 |             } else if (AstClass* const defp = VN_CAST(foundp->nodep(), Class)) {
      |           
```

and

```
V3PreLex_pregen.yy.cpp:3348:38: error: comparison of integers of different signs: 'yy_size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
 3348 |         if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
```

**Comment by paul-demo** [comment]
Not sure how to interpret this but Github gives it a green circle and says "passed" but my email says it failed:
https://github.com/verilator/verilator/actions/runs/16039642116/job/45258677639?pr=6153

Looks like the test-runner failing to exit cleanly because I see signs of both success and failure:
```
vltmt/t_udp_sequential: FAILED: Exec of obj_vltmt/t_udp_sequential/Vt_udp_sequential failed: %Error: t/t_udp_sequential.v:48: Verilog $stop
```

AND

```
*-* All Finished *-*
- t/t_udp_sequential.v:63: Verilog $finish
vltmt/t_udp_sequential: Self PASSED
```
