### ISSUE TITLE
Verilator compilation fails when coverage is enabled

### ISSUE THREAD

**Issue by sammy17** [verilator/verilator#3039]
I am using cocotb and Verilator setup to simulate a design. I am getting the following compilation error when I enable coverage (with --coverage option). The simulation proceeds fine when the coverage is disabled. 
```
Vtop__ALL.a(Vtop__163.o): In function `Vtop::_eval(Vtop__Syms*)':
Vtop__163.cpp:(.text+0x78c4): undefined reference to `Vtop::_sequent__TOP__117(Vtop__Syms*)'
Vtop__ALL.a(Vtop__107__Slow.o): In function `Vtop::_eval_initial(Vtop__Syms*)':
Vtop__107__Slow.cpp:(.text+0xb6): undefined reference to `Vtop::_initial__TOP__2(Vtop__Syms*)'
collect2: error: ld returned 1 exit status
```

I am using cocotb 1.5.2 with Verilator 4.106 2020-12-02 rev v4.106.

I tried with the latest Verilator version (v4.204) and I do not get this compilation error with that. However, the latest Verilator does not work with cocotb due to VPI related issues as confirmed in https://github.com/cocotb/cocotb/issues/2573#issuecomment-865420666

It will be great if someone can point out the specific commit that this issue is fixed, I can try that commit and check whether I can get it working with v4.106+fix for this issue.

**Comment by wsnyder** [comment]
I don't know which commit it is without a complex search.  Perhaps you could try a "git bisect" to find the commit?
