### ISSUE TITLE
V3Dfg__gen_type_tests compilation errors

### ISSUE THREAD

**Issue by paul-demo** [verilator/verilator#6674]
Top of tree no longer compiles on clang++11, as of recently (v5.042 did, so this regressed just within the last week or so).

```
./V3Dfg__gen_type_tests.h: In static member function ‘static bool DfgVertex::privateTypeTest(const DfgVertex*) [with T = DfgVertexBinary]’:
./V3Dfg__gen_type_tests.h:64:131: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 template<> inline bool DfgVertex::privateTypeTest<DfgVertexBinary>(const DfgVertex* vtxp) { return static_cast<int>(vtxp->type()) >= static_cast<int>(VDfgType::firstVertexBinary) && static_cast<int>(vtxp->type()) <= static_cast<int>(VDfgType::lastVertexBinary); }
                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [V3DfgBreakCycles.o] Error 1
```

**Comment by paul-demo** [comment]
Disregard; I screwed up my compiler selection.
