### ISSUE TITLE
Large array initialisation produces invalid C++

### ISSUE THREAD

**Issue by jsutton101** [verilator/verilator#6904]
When an unpacked array is > 256 deep and > 64 wide, it produces invalid C++ that is unable to be compiled.

Version: 5.044 and master

Example:

```
module test_module (
        output logic [64:0] output_vec [257]
    );

    assign output_vec = '{default: '0};

endmodule
```
produces the C++
```
VL_ATTR_COLD void Vtest_module___024root___eval_initial__TOP(Valu___024root* vlSelf) {
...
    VlWide<3>/*95:0*/ __Vtemp_1;
...
    __Vtemp_1[0U] = 0U;
....
    {{
        __Vtemp_1,
        __Vtemp_257
    }};
}
```
This results in the compiler (gcc-14) error
```
.../test_module-gen/Vtest_module___024root__0__Slow.cpp:1314:20: error: expected ';' before '}' token
 1314 |         __Vtemp_257
      |                    ^
      |                    ;
 1315 |     }};
      |     ~
.../test_module-gen/Vtest_module___024root__0__Slow.cpp:1315:5: error: right operand of comma operator has no effect [-Werror=unused-value]
 1315 |     }};
```
Reducing the packed width to 64 or less or the unpacked width to 256 or less results in correct C++

This bug appears to be introduced in e2f5854 and 19bbeb2 as reverting these two commits causes verilator to produce valid output again

**Comment by wsnyder** [comment]
For pull see #6918
